### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by Collbrothers** [BlazifyOrg/blazify.github.io#1]
### UX / UI:
- [ ] Making the teams tab responsive
- [ ] Make the home page look more pleasent
### Structures:
- [ ] Splitting every 'tab' into their own component
- [ ] Adding a dialog for each members 'more' view
- [ ] Add 'Projects' tab
### General
- [ ] SEO
- [ ] Home
- [ ] About
- [ ] Projects
- [ ] Team
- [ ] Contact Us
- [ ] /projects/:id
- [ ] Teams Page Dialogue boxes
